// Generated by gencpp from file blob_segmentation/Centroid.msg
// DO NOT EDIT!


#ifndef BLOB_SEGMENTATION_MESSAGE_CENTROID_H
#define BLOB_SEGMENTATION_MESSAGE_CENTROID_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace blob_segmentation
{
template <class ContainerAllocator>
struct Centroid_
{
  typedef Centroid_<ContainerAllocator> Type;

  Centroid_()
    : x(0)
    , y(0)
    , area(0)  {
    }
  Centroid_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , area(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::blob_segmentation::Centroid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::blob_segmentation::Centroid_<ContainerAllocator> const> ConstPtr;

}; // struct Centroid_

typedef ::blob_segmentation::Centroid_<std::allocator<void> > Centroid;

typedef boost::shared_ptr< ::blob_segmentation::Centroid > CentroidPtr;
typedef boost::shared_ptr< ::blob_segmentation::Centroid const> CentroidConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::blob_segmentation::Centroid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::blob_segmentation::Centroid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::blob_segmentation::Centroid_<ContainerAllocator1> & lhs, const ::blob_segmentation::Centroid_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::blob_segmentation::Centroid_<ContainerAllocator1> & lhs, const ::blob_segmentation::Centroid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace blob_segmentation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::blob_segmentation::Centroid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::blob_segmentation::Centroid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blob_segmentation::Centroid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::blob_segmentation::Centroid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blob_segmentation::Centroid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::blob_segmentation::Centroid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::blob_segmentation::Centroid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b3ff87eeaf6039576da4242a0369417e";
  }

  static const char* value(const ::blob_segmentation::Centroid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb3ff87eeaf603957ULL;
  static const uint64_t static_value2 = 0x6da4242a0369417eULL;
};

template<class ContainerAllocator>
struct DataType< ::blob_segmentation::Centroid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "blob_segmentation/Centroid";
  }

  static const char* value(const ::blob_segmentation::Centroid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::blob_segmentation::Centroid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"int32 area\n"
;
  }

  static const char* value(const ::blob_segmentation::Centroid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::blob_segmentation::Centroid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Centroid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::blob_segmentation::Centroid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::blob_segmentation::Centroid_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLOB_SEGMENTATION_MESSAGE_CENTROID_H
